[package]
name = "mastodon-async-entities"

version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
log = { version = "0.4", features = ["kv_unstable", "serde", "std", "kv_unstable_serde", "kv_unstable_std"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
time = { version = "0.3", features = ["parsing", "serde", "formatting"] }
static_assertions = "1"
url = { version = "2.3.1", features = ["serde"] }
classic-bitfield = { version = "0.2", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0.91"
